# Configuration Jekyll pour GitHub Pages - Blog iZiChange

# Informations du site
title: "Blog iZiChange - Expertise Digital & Formation IA"
description: "Blog iZiChange Occitanie : expertise accompagnement digital, transformation IA, formation TPE PME. Conseils et guides pour dirigeants d'entreprises."
url: "https://izichange.github.io"
baseurl: "/blog"

# Informations auteur/organisation
author:
  name: "iZiChange"
  email: "contact@izichange.fr"
  url: "https://www.izichange.fr"

# Configuration SEO
lang: fr-FR
timezone: Europe/Paris

# Plugins GitHub Pages
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Configuration des permaliens
permalink: /articles/:title/

# Configuration des collections
collections:
  articles:
    output: true
    permalink: /articles/:name/

# Défauts pour les pages
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      author: "iZiChange"
  - scope:
      path: "articles"
      type: "pages"
    values:
      layout: "article"
      author: "iZiChange"

# Configuration du thème
theme: minima

# Variables personnalisées
company:
  name: "iZiChange"
  location: "Occitanie, France"
  phone: "+33 (0)6 86 84 64 29"
  email: "contact@izichange.fr"
  website: "https://www.izichange.fr"

# Couleurs de la charte graphique
colors:
  primary: "#1F2A63"
  accent: "#F39448"
  background: "#FFFFFF"
  text: "#333333"

# Configuration des réseaux sociaux
social:
  linkedin: "https://linkedin.com/company/izichange"

# Configuration SEO avancée
seo:
  keywords: ["IA", "formation", "TPE", "PME", "transformation digitale", "Occitanie", "accompagnement digital"]

# Exclusions
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - .sass-cache/
  - .jekyll-cache/
  - .jekyll-metadata

# Configuration markdown
markdown: kramdown
highlighter: rouge

# Configuration des flux RSS
feed:
  excerpt_only: true
